# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76ef3ced8773e349e74a409abd836bf6146b2c3b5559ebce6745043b69d79128fa2e0d398633809ca95962ae8e66932085905178d2102016532b59ad24b74dcf

test:
  secret_key_base: 54d71c0058ef9054fe9d7881ef09714831bc55f55eb464a796f54929818ab1164e6286f921f996d7812e80fa5242173aae1ccc39fa17d3e32c6e28e0b15e0107

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
